name: fft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arabic_reshaper=2.1.3=pyhd8ed1ab_0
  - argon2-cffi=20.1.0=py39h27cfd23_1
  - asn1crypto=1.5.1=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - automat=20.2.0=py_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.2=py39hb9d737c_0
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bumps=0.9.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.14.6=py39he32792d_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.1.3=py39hf3d152e_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - configparser=5.2.0=pyhd8ed1ab_0
  - constantly=15.1.0=py_0
  - cryptography=37.0.2=py39hd97740a_0
  - cssselect2=0.2.1=pyh9f0ad1d_1
  - cudatoolkit=11.6.0=hecad31d_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py39hf3d152e_5
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h7b6447c_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.18.4=h29181c9_0
  - gstreamer=1.18.5=h76c114f_0
  - h5py=3.3.0=nompi_py39h98ba4bc_100
  - hdf5=1.10.6=nompi_h3c11f04_101
  - html5lib=1.1=pyh9f0ad1d_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - incremental=21.3.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py39h06a4308_0
  - ipython=8.4.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.4.0=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_7
  - jupyter_client=7.2.2=py39h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libclang=11.1.0=default_ha53f305_1
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h516909a_0
  - libllvm11=11.1.0=hf817b99_2
  - libpng=1.6.37=hbc83047_0
  - libpq=13.3=hd57d9b9_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=h2818925_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libxslt=1.1.33=h15afd5d_2
  - lxml=4.8.0=py39hb9d737c_2
  - lz4-c=1.9.3=h295c915_1
  - mako=1.2.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.5.1=py39h06a4308_1
  - matplotlib-base=3.5.1=py39ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.4.4=py39h06a4308_0
  - nbformat=5.3.0=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - nettle=3.6=he412f7d_0
  - notebook=6.4.11=py39h06a4308_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.69=hb5efdd6_1
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.22.3=py39he7a7128_0
  - numpy-base=1.22.3=py39hf524024_0
  - ocl-icd=2.3.1=h7f98852_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1o=h166bdaf_0
  - oscrypto=1.2.1=pyhd3deb0d_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39h6a678d5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - periodictable=1.5.2=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.1.2=py39h06a4308_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhanko=0.13.2=pyhd8ed1ab_0
  - pyhanko-certvalidator=0.19.5=pyhd8ed1ab_0
  - pyopencl=2022.1.5=py39hac2352c_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pypdf3=1.0.6=pyhd8ed1ab_0
  - pyqt=5.12.3=py39h03dd644_4
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.12=h12debd9_1
  - python-bidi=0.4.2=py_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-tzdata=2022.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytools=2022.1.12=pyhd8ed1ab_0
  - pytorch=1.12.0=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pytz-deprecation-shim=0.1.0.post0=py39hf3d152e_2
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39h6a678d5_0
  - qrcode=7.3.1=pyhd8ed1ab_0
  - qt=5.12.9=hda022c4_4
  - qt5reactor=0.6.3=pyh9f0ad1d_0
  - qtconsole=5.3.1=py39h06a4308_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - reportlab=3.5.68=py39he59360d_1
  - requests=2.28.1=pyhd8ed1ab_0
  - sasmodels=1.0.6=pyhd8ed1ab_0
  - sasview=5.0.4.post36=py39hac2352c_0
  - scikit-learn=1.0.2=py39h51133e4_1
  - scipy=1.7.3=py39hc147768_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=py_0
  - setuptools=61.2.0=py39h06a4308_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svglib=1.3.0=pyhd8ed1ab_0
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.0=py39_cu116
  - torchvision=0.13.0=py39_cu116
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - twisted=22.4.0=py39hb9d737c_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022a=hda174b7_0
  - tzlocal=4.2=py39hf3d152e_1
  - uritools=4.0.0=pyhd8ed1ab_0
  - urllib3=1.26.10=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - xhtml2pdf=0.2.8=py39hf3d152e_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h7f8727e_2
  - zope.interface=5.4.0=py39hb9d737c_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
